using DotNetCoreFood.Data;
using DotNetCoreFood.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DotNetCoreFood.Services
{
    public class SqlRestaurantData : IRestaurantData
    {
        private readonly DotNetCoreFoodDbContext _context;

        public Restaurant Add(Restaurant restaurant)
        {
            _context.Restaurants.Add(restaurant);
            _context.SaveChanges(); // commits
            return restaurant;      // Id auto-generated by SQL Server
        }

        public Restaurant Get(int id)
        {
            return _context.Restaurants.FirstOrDefault(r => r.Id == id);
        }

        public IEnumerable<Restaurant> GetAll()
        {
            return _context.Restaurants.OrderBy(r => r.Name);
        }

        public Restaurant Update(Restaurant restaurant)
        {
            _context.Attach(restaurant).State = EntityState.Modified;
            _context.SaveChanges();
            return restaurant;
        }

        public SqlRestaurantData(DotNetCoreFoodDbContext context)
        {
            _context = context;
        }
    }
}
